server:
  port: 8888
spring:
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.20.186/axhub?useUnicode=true&characterEncoding=utf8&useSSL=false
      driver: com.cj.mysql.jdbc.driver